# Generated by Django 2.2.14 on 2021-08-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('Newsletter', 'Newsletter')], default='Google', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
